// Generated by Selenium IDE
package com.example.selenium;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class RozetkaLoginTest {
    JavascriptExecutor js;
    private WebDriver driver;
    private Map<String, Object> vars;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void rozetkalogin() {
        driver.get("https://rozetka.com.ua/");
        driver.manage().window().setSize(new Dimension(1680, 1027));
        driver.findElement(By.linkText("войдите в личный кабинет")).click();
        driver.findElement(By.id("auth_email")).sendKeys("иван@mail.com");
        driver.findElement(By.id("auth_pass")).sendKeys("P@ssw0rd");
        driver.findElement(By.cssSelector(".auth-modal__submit")).click();
        driver.findElement(By.name("search")).sendKeys("MacBook Air 2020");
        driver.findElement(By.cssSelector(".search-form__submit")).click();
        driver.findElement(By.xpath("(//a[contains(@href,\'apple_macbook_air_2020\')])")).click();

        assertThat(driver.findElement(By.cssSelector(".product-prices__big")).getText(), is("33 999₴"));

        driver.findElement(By.linkText("иван")).click();
        driver.findElement(By.linkText("Выход")).click();
        driver.close();
    }
}
